version: "3"
services:
  src:
    build:
      context: ./
      dockerfile: DockerFile
    command: npm i
    ports:
      - 8080:8000
    depends_on:
      - postgres
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ong@example.com
      PGADMIN_DEFAULT_PASSWORD: ong
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "54322:80"
    depends_on:
      - postgres